# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Writes /etc/default/grub in the target system before `bootloader`
# runs `grub-mkconfig`.
---
overwrite: false
prefer_grub_d: false
keep_distributor: false

kernel_params: [ "quiet", "splash", "loglevel=3", "udev.log_level=3" ]

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: false
    GRUB_TERMINAL_OUTPUT: "console"
    GRUB_DISABLE_RECOVERY: false
    GRUB_DISABLE_OS_PROBER: false

always_use_defaults: false
