# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# User and hostname configuration for WilburOS.
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - name: wheel
      must_exist: false
      system: true
    - lp
    - video
    - network
    - storage
    - audio
    - power
    - sys
    - optical
    - scanner
    - rfkill
    - input

sudoersGroup: wheel
sudoersConfigureWithGroup: false

autologinGroup: autologin

setRootPassword: true
doReusePassword: true

displayAutologin: true
doAutologin: false

passwordRequirements:
    nonempty: true

allowWeakPasswords: true
allowWeakPasswordsDefault: true

user:
  shell: /bin/bash
  forbidden_names: [ root ]
  home_permissions: "o750"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "wilburos"
  forbidden_names: [ localhost ]
